### ISSUE TITLE
[BUG] 22_deployment_on_azure_kubernetes_service.ipynb - AKS deployment fails

### ISSUE THREAD

**Issue by chennebe** [microsoft/computervision-recipes#499] opened 2020-02-17 22:55 UTC
### Description

Running classification notebook 22 fails at cell 9 while trying to deploy service. It returns an InvalidDeploymentTemplate error, specifying that the regional cores quota was exceeded:

[{'error': {'code': 'BadArgument', 'message': 'InvalidTemplateDeployment: Details: RequestId: 9618e9b6-5a5e-4b84-92c0-2b7b69144777\nError code: \'InvalidTemplateDeployment\'. Target: \'\'. Message: \'The template deployment \'caae618f-2c9f-4619-b088-48ba57333c1f\' is not valid according to the validation procedure. The tracking id is \'9618e9b6-5a5e-4b84-92c0-2b7b69144777\'. See inner errors for details.\'\n    Error code: \'QuotaExceeded\'. Target: \'\'. Message: \'Provisioning of resource(s) for container service imgclass-aks-cpu9fe63651 in resource group docs-aml failed. Message: {\n      "code": "QuotaExceeded",\n      "message": "Provisioning of resource(s) for container service imgclass-aks-cpu9fe63651 in resource group docs-aml failed. Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus2, Current Limit: 4, Current Usage: 0, Additional Required: 12, (Minimum) New Limit Required: 12. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2221e79250-290a-42ea-95b6-46401877475b%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.. Details: "\n     }. Details: \'\n'}}]

Note: This was tested using the free azure credits/subscription, maybe this is contributing to the error?

### In which platform does it happen?

Tested on Linux and Windows machines.

### How do we replicate the issue?

Run through classification notebook 20 and 22.

**Comment by youngpark** [comment] 2020-02-19 18:35
Hi @chennebe - as you correctly noted above, the error is caused by not having enough regional cores quota.

Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - **Deployment Model: Resource Manager, Location: eastus2, Current Limit: 4, Current Usage: 0, Additional Required: 12, (Minimum) New Limit Required: 12**. Submit a request for Quota increase.

We'll close this issue for now, but if you continue to see this issue with a different subscription, feel free to open another one.

**Closed by youngpark** 2020-02-19 18:35 UTC
Labels: bug
